version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-microservice
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: auth-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
